twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        '%kernel.project_dir%/bundles/ProductBundle/templates': ProductBundle
#        '%kernel.project_dir%/bundles/ProductBundle/templates/vote': DAO